# permissions for end users to view towerchallenges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: towerchallenge-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: towerofhanoi
    app.kubernetes.io/part-of: towerofhanoi
    app.kubernetes.io/managed-by: kustomize
  name: towerchallenge-viewer-role
rules:
- apiGroups:
  - webapp.hanoi.com
  resources:
  - towerchallenges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.hanoi.com
  resources:
  - towerchallenges/status
  verbs:
  - get
