apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xtowerchallenges.hanoi.com
spec:
  group: hanoi.com
  names:
    kind: XTowerChallenge
    plural: xtowerchallenges
    listKind: XTowerChallengeList
  claimNames:
    kind: TowerChallenge
    plural: towerchallenges
    singular: towerchallenge
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                discs:
                  type: integer
                  minimum: 1
                # Example of adding more spec fields if necessary
            status:
              type: object
              properties:
                phase:
                  type: string
                message:
                  type: string
