apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tower-challenge-operator
  namespace: tower-challenge
rules:
- apiGroups: ["hanoi.com"]
  resources: ["towerchallenges", "towerchallenges/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "create", "update"]
