apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tower-challenge-operator
  namespace: tower-challenge
subjects:
- kind: ServiceAccount
  name: tower-challenge-operator-sa
  namespace: tower-challenge
roleRef:
  kind: Role
  name: tower-challenge-operator
  apiGroup: rbac.authorization.k8s.io
