apiVersion: apps/v1
kind: Deployment
metadata:
  name: tower-challenge-operator
  namespace: tower-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tower-challenge-operator
  template:
    metadata:
      labels:
        name: tower-challenge-operator
    spec:
      serviceAccountName: tower-challenge-operator-sa
      containers:
      - name: tower-challenge-operator
        image: moefromthemo/tower-challenge-operator:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 6000
          name: metrics
        command:
        - /manager
        args:
        - "--leader-elect"
        - "--metrics-bind-address=:8080"
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: metrics
