# This deployment YAML has been modified for a technical assessment.
# The following flags have been commented out:
# - --zap-devel=true
# - --zap-encoder=console
# - --zap-log-level=info
# - --zap-stacktrace-level=info
# - --zap-time-encoding=iso8601

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tower-challenge-operator
  namespace: tower-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tower-challenge-operator
  template:
    metadata:
      labels:
        name: tower-challenge-operator
    spec:
      serviceAccountName: tower-challenge-operator-sa
      containers:
      - name: tower-challenge-operator
        image: moefromthemo/tower-challenge-operator:v1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: metrics
        command:
        - /manager
        args:
        # - "--leader-elect"   - leader election is good for a prodcution environment but we don't need for a assesment
        # - "--leader-election-retry-period=2s"
        - "--metrics-bind-address=:8080"
        # - "--zap-devel=true"  # Enable development mode
        # - "--zap-encoder=console"  # Use console encoder for better readability
        # - "--zap-log-level=info"  # Log at info level for more detailed information
        # - "--zap-stacktrace-level=info"  # Capture stack traces at info level for better debugging
        # - "--zap-time-encoding=iso8601"  # Use human-readable timestamps
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
