apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: towerchallenges.hanoi.com
spec:
  group: hanoi.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                numDisks:
                  type: integer
                  minimum: 1
            status:
              type: object
              properties:
                phase:
                  type: string
                configMapsCreated:
                  type: boolean
                configMapNames:
                  type: array
                  items:
                    type: string
                startTime:
                  type: string
                  format: date-time
                endTime:
                  type: string
                  format: date-time
                errorMessage:
                  type: string
                  nullable: true
  scope: Namespaced
  names:
    plural: towerchallenges
    singular: towerchallenge
    kind: TowerChallenge
    shortNames:
      - tc
