apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: discmovesequences.hanoi.com
spec:
  group: hanoi.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sequenceDetails:
                  type: string  # Just an example field
  scope: Namespaced
  names:
    plural: discmovesequences
    singular: discmovesequence
    kind: DiscMoveSequence
