apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: tower-of-hanoi-composition
spec:
  compositeTypeRef:
    apiVersion: hanoi.com/v1alpha1
    kind: TowerChallenge
  resources:
    - name: initialize-moves
      base:
        apiVersion: batch/v1
        kind: Job
        spec:
          template:
            spec:
              containers:
                - name: init-moves
                  image: yourorg/init-moves:latest
                  args: ["$(DISCS)"]
              restartPolicy: Never
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.discs"
          toFieldPath: "spec.template.spec.containers[0].args[0]"
