apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: towerchallenges.hanoi.com
spec:
  group: hanoi.com
  names:
    kind: TowerChallenge
    plural: towerchallenges
    singular: towerchallenge
    shortNames:
      - tc
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                discs:
                  type: integer
                  minimum: 1
            status:
              type: object
              properties:
                lastUpdated:
                  type: string
                  format: date-time
                  description: "Timestamp of the last status update"
                message:
                  type: string
                  description: "Descriptive message about the current state"
                phase:
                  type: string
                  description: "Current phase of the challenge"
      subresources:
        status: {}
