apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: towerchallenges.hanoi.com
spec:
  group: hanoi.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                discs:
                  type: integer
                  minimum: 1
  scope: Namespaced
  names:
    plural: towerchallenges
    singular: towerchallenge
    kind: TowerChallenge
    shortNames:
    - tc
