apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: towerchallenge-composition
  labels:
    purpose: tower-of-hanoi-disks-challenge-composition
spec:
  writeConnectionSecretsToNamespace: tower-challenge
  compositeTypeRef:
    apiVersion: tower.hanoi.com/v1alpha1
    kind: CompositeResourceTowerChallenge
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: "metadata.name"
      toFieldPath: "metadata.name"
  resources:
  - name: towerchallenge
    base:
      apiVersion: webapp.hanoi.com/v1alpha1
      kind: TowerChallenge
      metadata:
        labels:
          app: tower-of-hanoi
        name: "$(metadata.name)"
      spec:
        discs: 3
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: "spec.discs"
      toFieldPath: "spec.discs"
    readinessChecks:
    - type: "MatchString"
      fieldPath: "status.phase"
      matchString: "Completed"
  - name: logging
    base:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: tower-challenge
        labels:
          app: tower-of-hanoi-logs
        name: "$(metadata.name)-logs"
      data:
        loglevel: "info"
